### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by niceque** [arguiot/DisplayJS#8] opened 2017-08-11 11:24 UTC
![displayjs test - google chrome 2017-08-11 14 23 12](https://user-images.githubusercontent.com/6256044/29211260-b726557e-7ea0-11e7-86a8-d9782e3ff4a6.png)
Why so?

**Comment by arguiot** [comment] 2017-08-11 11:29
Thanks 🙏 reporting this error, this bug is caused by exporting the DisplayJS module everywhere.

I already noticed this error and it will be fixed in the next release 😊.

**Comment by niceque** [comment] 2017-08-11 11:30
Can i work ignoring this issue? functions are working properly

**Closed by arguiot** 2017-08-11 11:29 UTC

**Comment by arguiot** [comment] 2017-08-11 11:31
Yes 😊, functions are normally working, if you find other bugs 🐜 don’t hesitate to reports them.

By the way, you can star ⭐️ the project and be the 200 stargazer

**Comment by niceque** [comment] 2017-08-11 11:38
Thank you!
